### ISSUE TITLE
图片全屏

### ISSUE THREAD

**Issue by yizibi** [zhengwenming/WMPhotoBrowser#1]
单击后，导航栏隐藏，双击放大，图片没有全部铺满，把状态栏分开了，这个是系统适配还是frame的原因，还没具体看代码，还是你就是这样设计的，6s, ios 10.3
@zhengwenming

**Comment by zhengwenming** [comment]
看到了bug，我刚提交，测试的时候用iPhone X测试的，我fix一下这个bug。很快就会更新掉这个bug。

**Comment by zhengwenming** [comment]
bug已经修复，请放心使用。
